In [4]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [5]:
df=sns.load_dataset("iris")

In [6]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [7]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X=df.drop("species",axis=1)
y=df['species']

In [11]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.33,random_state=42)

In [12]:
from  sklearn.neighbors import KNeighborsClassifier

In [13]:
model_knn=KNeighborsClassifier(n_neighbors=13)

In [14]:
model_knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=13)

In [15]:
model_knn.score(X_test,y_test)

1.0

In [16]:
from sklearn.svm import SVC

In [17]:
model_svm=SVC(gamma='auto')

In [18]:
model_svm.fit(X_train,y_train)

SVC(gamma='auto')

In [19]:
model_svm.score(X_test,y_test)

1.0

#Using Grid Search CV

In [20]:
from sklearn.model_selection import GridSearchCV

In [21]:
classifier = GridSearchCV((model_svm),{
    'C':[10,20,30,40],
    'kernel':['rbf','linear']
},cv=5,return_train_score=False)

In [22]:
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [10, 20, 30, 40], 'kernel': ['rbf', 'linear']})

In [23]:
classifier.cv_results_

{'mean_fit_time': array([0.00251107, 0.00250177, 0.00231347, 0.00198579, 0.00202055,
        0.00185819, 0.00175638, 0.00167451]),
 'std_fit_time': array([2.78302420e-04, 1.41213165e-04, 2.63291051e-04, 4.73528349e-05,
        5.49275013e-05, 3.29657637e-05, 2.49082498e-05, 4.02470335e-05]),
 'mean_score_time': array([0.00189295, 0.0019206 , 0.00157547, 0.00144629, 0.0014904 ,
        0.00139723, 0.00131049, 0.00128336]),
 'std_score_time': array([2.27506429e-04, 2.57824163e-04, 1.60209267e-04, 2.77830389e-05,
        1.24885827e-05, 3.81033171e-05, 3.11015551e-05, 1.41809158e-05]),
 'param_C': masked_array(data=[10, 10, 20, 20, 30, 30, 40, 40],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'},
  {'C': 40, 'kernel': 'rbf'},
  {'C': 40, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 1.        , 0.96666667, 1.        , 0.96666667,
        1.        , 1.        , 1.        ]),
 'split1_test_score': array([1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 0.96666667, 1.        ]),
 'split2_test_score': array([0.96666667, 0.9       , 0.9       , 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 0.93333333,
        0.9       , 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.97333333, 0.96666667, 0.96666667, 0.96      ,
        0.96      , 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.03887301, 0.03651484, 0.0421637 , 0.03887301,
        0.04898979, 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 2, 3, 4, 5, 5, 5, 5], dtype=int32)}

In [24]:
result = pd.DataFrame(classifier.cv_results_)

In [25]:
result

   mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0       0.002511      0.000278  ...        0.016330                1
1       0.002502      0.000141  ...        0.038873                2
2       0.002313      0.000263  ...        0.036515                3
3       0.001986      0.000047  ...        0.042164                4
4       0.002021      0.000055  ...        0.038873                5
5       0.001858      0.000033  ...        0.048990                5
6       0.001756      0.000025  ...        0.038873                5
7       0.001675      0.000040  ...        0.048990                5

[8 rows x 15 columns]

In [26]:
result[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0       10          rbf         0.980000
1       10       linear         0.973333
2       20          rbf         0.966667
3       20       linear         0.966667
4       30          rbf         0.960000
5       30       linear         0.960000
6       40          rbf         0.960000
7       40       linear         0.960000

In [27]:
from sklearn.model_selection import RandomizedSearchCV

In [37]:
classifier_r = RandomizedSearchCV((model_svm),{
    'C':[1,10,20,30],
    'kernel':['rbf','linear']
},n_iter=4,cv=5,return_train_score=False)

In [38]:
classifier_r.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [39]:
classifier_r.cv_results_

{'mean_fit_time': array([0.00219631, 0.00227127, 0.00237112, 0.00196776]),
 'std_fit_time': array([1.89821380e-04, 9.38797307e-05, 2.30612293e-04, 5.29354968e-05]),
 'mean_score_time': array([0.00161328, 0.00164824, 0.00164013, 0.00147181]),
 'std_score_time': array([1.39862573e-04, 4.71730063e-05, 4.89752386e-05, 5.69670550e-05]),
 'param_kernel': masked_array(data=['linear', 'rbf', 'rbf', 'linear'],
              mask=[False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_C': masked_array(data=[20, 30, 1, 10],
              mask=[False, False, False, False],
        fill_value=999999),
 'params': [{'kernel': 'linear', 'C': 20},
  {'kernel': 'rbf', 'C': 30},
  {'kernel': 'rbf', 'C': 1},
  {'kernel': 'linear', 'C': 10}],
 'split0_test_score': array([1.        , 0.96666667, 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1.]),
 'split2_test_score': array([0.9       , 0.9       , 0.96666667, 0.9       ]),
 'split3_test_score': array([0.93333333, 0.93333333, 0.96666667, 0.96666667]),
 'split4_test_score': array([1., 1., 1., 1.]),
 'mean_test_score': array([0.96666667, 0.96      , 0.98      , 0.97333333]),
 'std_test_score': array([0.0421637 , 0.03887301, 0.01632993, 0.03887301]),
 'rank_test_score': array([3, 4, 1, 2], dtype=int32)}

In [40]:
result_r = pd.DataFrame(classifier_r.cv_results_)

In [41]:
result_r

   mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0       0.002196      0.000190  ...        0.042164                3
1       0.002271      0.000094  ...        0.038873                4
2       0.002371      0.000231  ...        0.016330                1
3       0.001968      0.000053  ...        0.038873                2

[4 rows x 15 columns]

In [42]:
result_r[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0       20       linear         0.966667
1       30          rbf         0.960000
2        1          rbf         0.980000
3       10       linear         0.973333